name: pre-commit

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        version: 3.6
        architecture: x64
    - uses: actions/cache@v1.2.0
      with:
        path: ~/.cache/pre-commit
        key: pre-commit|${{ hashFiles('.pre-commit-config.yaml') }}
    - uses: pre-commit/action@v2.0.2
